### ISSUE TITLE
TypeError when trying to upload patch series

### ISSUE THREAD

**Issue by aethanyc** [mystor/phlay#23]
I'm using `phlay @~4..@`  to upload my patches with four parts, and got the following exception.

```
Traceback (most recent call last):
  File "/home/tlin/Projects/phlay/phlay", line 918, in <module>
    main()
  File "/home/tlin/Projects/phlay/phlay", line 910, in main
    process_args(args)
  File "/home/tlin/Projects/phlay/phlay", line 857, in process_args
    txn['value'] += "\n\nDepends on " + parent.revision.revid
TypeError: must be str, not int
```

I guess `parent.revision.revid` should be wrapped by `str()`?  (I'm on phlay master branch with SHA 1cc1931)

**Comment by mystor** [comment]
Oops - my bad. Should be fixed in 2c21a71
