### ISSUE TITLE
cinnabar's metadata can be out of date

### ISSUE THREAD

**Issue by ehsan** [mystor/phlay#34]
Here is an error I got right after upgrading cinnabar:

```
$ phlay  HEAD
Calculating Hg Changesets
ERROR:root:Git-cinnabar metadata needs upgrade. Please run `git cinnabar upgrade`.
Traceback (most recent call last):
  File "/home/ehsan/bin/phlay", line 944, in <module>
    main()
  File "/home/ehsan/bin/phlay", line 936, in main
    process_args(args)
  File "/home/ehsan/bin/phlay", line 767, in process_args
    ensure_hg_hashes(push)
  File "/home/ehsan/bin/phlay", line 673, in ensure_hg_hashes
    f"{current.commit_hash}..{to_hg[-1].commit_hash}"])
  File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'cinnabar', 'bundle', '--version', '1', '/tmp/tmpebsg6vkt/bundle.hg', '008068e848c6d4bf814ed2264aa4cb7bf658ace7..2f0b1cee860039790cf680428706bcdaf28c61a4']' returned non-zero exit status 1.
```

**Comment by amccreight** [comment]
I'm not sure what you are expecting phlay to do in this situation.

**Comment by mystor** [comment]
Closing as I'm not sure what we can do here.
